version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/London'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/drive:/mount:z
    command: '-s "Samba on Ubuntu;/mount;yes;no;no;username" -u "username;YourPassword" -p'
