version: '3'

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true 
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - ./config:/config
      - /mnt/drive/.watching:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
