version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./assets/:/www/assets
    ports:
      - 800:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
